"""The default plot setup."""

default_setup = {
    "default_cmap": "RdBu_r",
    "dpi": 200,
    "fig_scale": 1.0,
    "figsize": [24, 11],
    "length": ["m", "m"],
    "material_names": None,
    "num_levels": 11,
    "num_streamline_interp_pts": 50,
    "p_min": None,
    "p_max": None,
    "scale_type": "auto",
    "show_aspect_ratio": False,
    "show_element_edges": "MaterialIDs",
    "show_layer_bounds": True,
    "cmap_dict": {
        "displacement": "Greens",
        "temperature": "plasma",
        "pressure_active": ["yellow", "green"],
        "pressure": "Blues",
        "velocity": "coolwarm",
        "MaterialIDs": "tab20",
    },
    "cmap_dict_if_component": {"displacement": "PRGn"},
    "cmap_if_mask": ["yellow", "green"],
    "rcParams": {
        "font.weight": "normal",
        "font.family": "sans-serif",
        "font.size": 24,
        "axes.titlesize": "medium",
        "axes.labelsize": "medium",
        "axes.grid": False,
        "legend.fontsize": "medium",
        "xtick.labelsize": "medium",
        "ytick.labelsize": "medium",
        "axes.linewidth": 1,
        "lines.linewidth": 1,
        "legend.framealpha": 1,
        "mathtext.fontset": "dejavuserif",
    },
}
